spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    #url: jdbc:mysql://localhost:3306/lenos #?useUnicode=true&charcterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/lenos?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
  #config: classpath:logback-spring.xml
