spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://192.168.1.9:3306/blog?useUnicode=true&charcterEncoding=utf-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
  #config: classpath:logback-spring.xml
server:
  port: 8081